import type { RoleOpportunityArray, RoleOpportunityRecord } from './roleOpportunity.js';

export const rbExample: RoleOpportunityRecord = {
  playerId: '00-0036164',
  playerName: 'Kyren Williams',
  team: 'LAR',
  position: 'RB',
  season: 2024,
  week: 8,
  primaryRole: 'workhorse_rb',
  roleTags: ['early_down', 'three_down', 'red_zone_priority'],
  snapShare: 0.84,
  routeParticipation: 0.58,
  targetShare: 0.12,
  airYardShare: 0.04,
  carryShare: 0.76,
  rushAttemptShare: 0.76,
  teamOpportunityShare: 0.41,
  snaps: 54,
  routesRun: 22,
  targets: 5,
  carries: 19,
  redZoneTouchShare: 0.71,
  inside10TouchShare: 0.8,
  inside5TouchShare: 1,
  goalLineCarryShare: 1,
  redZoneTouches: 5,
  inside10Touches: 4,
  inside5Touches: 2,
  goalLineCarries: 2,
  confidence: {
    score: 0.93,
    tier: 'high',
    reasons: ['Stable snap lead', 'Handled all goal-line work', 'Routes remained above half of dropbacks'],
  },
  source: {
    model: 'tiber-role-opportunity-contract',
    modelVersion: 'v1.0.0',
    generatedAt: '2026-03-20T00:00:00Z',
    inputWindow: '2024 week 5-8 rolling window',
    notes: ['Shares are normalized to team opportunities for the scoped week.'],
  },
};

export const wrExample: RoleOpportunityRecord = {
  playerId: '00-0037834',
  playerName: 'Zay Flowers',
  team: 'BAL',
  position: 'WR',
  season: 2024,
  week: 10,
  primaryRole: 'slot_wr',
  roleTags: ['motion_usage', 'yards_after_catch', 'featured_receiver'],
  snapShare: 0.79,
  routeParticipation: 0.9,
  targetShare: 0.28,
  airYardShare: 0.26,
  carryShare: 0,
  rushAttemptShare: 0,
  teamOpportunityShare: 0.29,
  snaps: 52,
  routesRun: 37,
  targets: 10,
  carries: 0,
  redZoneTouchShare: 0.33,
  inside10TouchShare: 0.25,
  inside5TouchShare: 0,
  goalLineCarryShare: 0,
  redZoneTouches: 2,
  inside10Touches: 1,
  inside5Touches: 0,
  goalLineCarries: 0,
  confidence: {
    score: 0.88,
    tier: 'high',
    reasons: ['Top route rate among wide receivers', 'Target share held above 25%', 'Role stable across recent weeks'],
  },
  source: {
    model: 'tiber-role-opportunity-contract',
    modelVersion: 'v1.0.0',
    generatedAt: '2026-03-20T00:00:00Z',
    inputWindow: '2024 week 8-10 rolling window',
    notes: ['Carry fields remain zero for receivers without designed run usage.'],
  },
};

export const teExample: RoleOpportunityRecord = {
  playerId: '00-0035705',
  playerName: 'Trey McBride',
  team: 'ARI',
  position: 'TE',
  season: 2024,
  week: 11,
  primaryRole: 'move_te',
  roleTags: ['detached_alignments', 'featured_target', 'middle_of_field'],
  snapShare: 0.87,
  routeParticipation: 0.82,
  targetShare: 0.27,
  airYardShare: 0.22,
  carryShare: 0,
  rushAttemptShare: 0,
  teamOpportunityShare: 0.27,
  snaps: 61,
  routesRun: 34,
  targets: 11,
  carries: 0,
  redZoneTouchShare: 0.29,
  inside10TouchShare: 0.4,
  inside5TouchShare: 0.33,
  goalLineCarryShare: 0,
  redZoneTouches: 2,
  inside10Touches: 2,
  inside5Touches: 1,
  goalLineCarries: 0,
  confidence: {
    score: 0.86,
    tier: 'high',
    reasons: ['Route rate stayed above 80%', 'Commanded consistent red-zone work'],
  },
  source: {
    model: 'tiber-role-opportunity-contract',
    modelVersion: 'v1.0.0',
    generatedAt: '2026-03-20T00:00:00Z',
    inputWindow: '2024 week 9-11 rolling window',
    notes: ['Primary role distinguishes move usage from inline-heavy tight ends.'],
  },
};

export const qbExample: RoleOpportunityRecord = {
  playerId: '00-0034796',
  playerName: 'Jalen Hurts',
  team: 'PHI',
  position: 'QB',
  season: 2024,
  week: null,
  primaryRole: 'dual_threat_qb',
  roleTags: ['goal_line_runner', 'scramble_equity', 'high_leverage_usage'],
  snapShare: 1,
  routeParticipation: 0,
  targetShare: 0,
  airYardShare: 0,
  carryShare: 0.23,
  rushAttemptShare: 0.23,
  teamOpportunityShare: 0.23,
  snaps: 1128,
  routesRun: 0,
  targets: 0,
  carries: 150,
  redZoneTouchShare: 0.24,
  inside10TouchShare: 0.31,
  inside5TouchShare: 0.43,
  goalLineCarryShare: 0.45,
  redZoneTouches: 31,
  inside10Touches: 18,
  inside5Touches: 9,
  goalLineCarries: 5,
  confidence: {
    score: 0.91,
    tier: 'high',
    reasons: ['Full-season sample', 'Designed rush role is repeatable near goal line'],
  },
  source: {
    model: 'tiber-role-opportunity-contract',
    modelVersion: 'v1.0.0',
    generatedAt: '2026-03-20T00:00:00Z',
    inputWindow: null,
    notes: ['Null week indicates a full-season aggregate output.'],
  },
};

export const mixedRoleOpportunityExamples: RoleOpportunityArray = [
  rbExample,
  wrExample,
  teExample,
  qbExample,
];
