import type {
  ForgeWeeklyPlayerInput,
  ForgeWeeklyPlayerInputArray,
} from './forgeWeeklyPlayerInput.js';

export const forgeWeeklyWrExample: ForgeWeeklyPlayerInput = {
  playerId: '00-0037834',
  externalIds: {
    gsisId: '00-0037834',
    pfrId: 'FlowZa00',
  },
  playerName: 'Zay Flowers',
  position: 'WR',
  team: 'BAL',
  season: 2025,
  week: 12,
  asOf: '2026-03-18T12:00:00Z',
  snaps: 54,
  snapShare: 0.81,
  routesRun: 38,
  routeParticipation: 0.9,
  rushAttempts: 1,
  targets: 10,
  yardsPerRouteRun: 2.24,
  yardsPerCarry: 7,
  catchRate: 0.7,
  fantasyPointsPerOpportunity: 1.63,
  impliedTeamTotal: 25.5,
  spread: -3,
  opponentDefenseTier: 'average',
  expectedGameScript: 'neutral',
  injuryStatus: 'healthy',
  practiceParticipation: 'full',
  activeProjection: 0.99,
  roleVolatility: 0.24,
  sourceUpdatedAt: '2026-03-18T11:30:00Z',
  sourceSetId: 'forge-weekly-input-fixtures-v1',
  featureCoverage: 0.96,
  qualityFlags: ['manually-reviewed-fixture'],
  dataConfidenceHint: 'Stable route participation and target volume for a featured WR fixture.',
};

export const forgeWeeklyRbExample: ForgeWeeklyPlayerInput = {
  playerId: '00-0036164',
  externalIds: {
    gsisId: '00-0036164',
    pfrId: 'WillKy00',
  },
  playerName: 'Kyren Williams',
  position: 'RB',
  team: 'LAR',
  season: 2025,
  week: 12,
  asOf: '2026-03-18T12:00:00Z',
  snaps: 56,
  snapShare: 0.83,
  routesRun: 24,
  routeParticipation: 0.56,
  rushAttempts: 21,
  targets: 5,
  yardsPerRouteRun: 1.04,
  yardsPerCarry: 4.6,
  catchRate: 0.8,
  fantasyPointsPerOpportunity: 0.95,
  impliedTeamTotal: 24,
  spread: -2,
  opponentDefenseTier: 'strong',
  expectedGameScript: 'positive',
  injuryStatus: 'questionable',
  practiceParticipation: 'limited',
  activeProjection: 0.92,
  roleVolatility: 0.18,
  sourceUpdatedAt: '2026-03-18T11:30:00Z',
  sourceSetId: 'forge-weekly-input-fixtures-v1',
  featureCoverage: 0.95,
  qualityFlags: ['manual-injury-tag'],
};

export const forgeWeeklyQbExample: ForgeWeeklyPlayerInput = {
  playerId: '00-0034796',
  externalIds: {
    gsisId: '00-0034796',
    pfrId: 'HurtJa00',
  },
  playerName: 'Jalen Hurts',
  position: 'QB',
  team: 'PHI',
  season: 2025,
  week: 12,
  asOf: '2026-03-18T12:00:00Z',
  snaps: 67,
  snapShare: 1,
  routesRun: 0,
  routeParticipation: 0,
  rushAttempts: 12,
  targets: 0,
  yardsPerRouteRun: 0,
  yardsPerCarry: 5.1,
  catchRate: 0,
  fantasyPointsPerOpportunity: 0.84,
  impliedTeamTotal: 27.25,
  spread: -4.5,
  opponentDefenseTier: 'weak',
  expectedGameScript: 'positive',
  injuryStatus: 'healthy',
  practiceParticipation: 'full',
  activeProjection: 0.99,
  roleVolatility: 0.14,
  sourceUpdatedAt: '2026-03-18T11:30:00Z',
  sourceSetId: 'forge-weekly-input-fixtures-v1',
  featureCoverage: 0.94,
};

export const mixedForgeWeeklyExamples: ForgeWeeklyPlayerInputArray = [
  forgeWeeklyWrExample,
  forgeWeeklyRbExample,
  forgeWeeklyQbExample,
];
